
import mgear.core.pyqt as gqt
from mgear.vendor.Qt import QtCore, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(344, 635)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tools_groupBox = QtWidgets.QGroupBox(Form)
        self.tools_groupBox.setObjectName("tools_groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tools_groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.settings_pushButton = QtWidgets.QPushButton(self.tools_groupBox)
        self.settings_pushButton.setObjectName("settings_pushButton")
        self.verticalLayout_2.addWidget(self.settings_pushButton)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.duplicate_pushButton = QtWidgets.QPushButton(self.tools_groupBox)
        self.duplicate_pushButton.setObjectName("duplicate_pushButton")
        self.horizontalLayout.addWidget(self.duplicate_pushButton)
        self.dupSym_pushButton = QtWidgets.QPushButton(self.tools_groupBox)
        self.dupSym_pushButton.setObjectName("dupSym_pushButton")
        self.horizontalLayout.addWidget(self.dupSym_pushButton)
        self.extrCtl_pushButton = QtWidgets.QPushButton(self.tools_groupBox)
        self.extrCtl_pushButton.setObjectName("extrCtl_pushButton")
        self.horizontalLayout.addWidget(self.extrCtl_pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.build_pushButton = QtWidgets.QPushButton(self.tools_groupBox)
        self.build_pushButton.setObjectName("build_pushButton")
        self.verticalLayout_2.addWidget(self.build_pushButton)
        self.verticalLayout_3.addWidget(self.tools_groupBox)
        self.list_groupBox = QtWidgets.QGroupBox(Form)
        self.list_groupBox.setObjectName("list_groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.list_groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.search_lineEdit = QtWidgets.QLineEdit(self.list_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_lineEdit.sizePolicy().hasHeightForWidth())
        self.search_lineEdit.setSizePolicy(sizePolicy)
        self.search_lineEdit.setObjectName("search_lineEdit")
        self.verticalLayout.addWidget(self.search_lineEdit)
        self.splitter = QtWidgets.QSplitter(self.list_groupBox)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.component_listView = DragQListView(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.component_listView.sizePolicy().hasHeightForWidth())
        self.component_listView.setSizePolicy(sizePolicy)
        self.component_listView.setMinimumSize(QtCore.QSize(0, 0))
        self.component_listView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.component_listView.setProperty("showDropIndicator", False)
        self.component_listView.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.component_listView.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.component_listView.setAlternatingRowColors(True)
        self.component_listView.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.component_listView.setObjectName("component_listView")
        self.info_plainTextEdit = QtWidgets.QPlainTextEdit(self.splitter)
        self.info_plainTextEdit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.info_plainTextEdit.sizePolicy().hasHeightForWidth())
        self.info_plainTextEdit.setSizePolicy(sizePolicy)
        self.info_plainTextEdit.setMinimumSize(QtCore.QSize(0, 50))
        self.info_plainTextEdit.setMaximumSize(QtCore.QSize(16777215, 100))
        self.info_plainTextEdit.setBaseSize(QtCore.QSize(0, 50))
        self.info_plainTextEdit.setUndoRedoEnabled(False)
        self.info_plainTextEdit.setReadOnly(True)
        self.info_plainTextEdit.setPlainText("")
        self.info_plainTextEdit.setObjectName("info_plainTextEdit")
        self.verticalLayout.addWidget(self.splitter)
        self.draw_pushButton = QtWidgets.QPushButton(self.list_groupBox)
        self.draw_pushButton.setObjectName("draw_pushButton")
        self.verticalLayout.addWidget(self.draw_pushButton)
        self.showUI_checkBox = QtWidgets.QCheckBox(self.list_groupBox)
        self.showUI_checkBox.setChecked(True)
        self.showUI_checkBox.setObjectName("showUI_checkBox")
        self.verticalLayout.addWidget(self.showUI_checkBox)
        self.verticalLayout_3.addWidget(self.list_groupBox)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(gqt.fakeTranslate("Form", "Form", None, -1))
        self.tools_groupBox.setTitle(gqt.fakeTranslate("Form", "Guide Tools", None, -1))
        self.settings_pushButton.setWhatsThis(gqt.fakeTranslate("Form", "<html><head/><body><p>Open Component/Guide root settings window.</p></body></html>", None, -1))
        self.settings_pushButton.setText(gqt.fakeTranslate("Form", "Settings", None, -1))
        self.duplicate_pushButton.setToolTip(gqt.fakeTranslate("Form", "<html><head/><body><p>Duplicate selected component.</p></body></html>", None, -1))
        self.duplicate_pushButton.setText(gqt.fakeTranslate("Form", "Duplicate", None, -1))
        self.dupSym_pushButton.setToolTip(gqt.fakeTranslate("Form", "<html><head/><body><p>Duplicate symmetrical selected component.</p></body></html>", None, -1))
        self.dupSym_pushButton.setText(gqt.fakeTranslate("Form", "Dupl. Sym.", None, -1))
        self.extrCtl_pushButton.setToolTip(gqt.fakeTranslate("Form", "<html><head/><body><p>Extract Selected Controls and store as control Buffer.</p></body></html>", None, -1))
        self.extrCtl_pushButton.setText(gqt.fakeTranslate("Form", "Extr. Ctl.", None, -1))
        self.build_pushButton.setToolTip(gqt.fakeTranslate("Form", "<html><head/><body><p>Build rig from selection</p></body></html>", None, -1))
        self.build_pushButton.setWhatsThis(gqt.fakeTranslate("Form", "<html><head/><body><p>Open Component/Guide root settings window.</p></body></html>", None, -1))
        self.build_pushButton.setText(gqt.fakeTranslate("Form", "Build From Selection", None, -1))
        self.list_groupBox.setTitle(gqt.fakeTranslate("Form", "Component List", None, -1))
        self.draw_pushButton.setToolTip(gqt.fakeTranslate("Form", "<html><head/><body><p>Draw selected component.</p></body></html>", None, -1))
        self.draw_pushButton.setText(gqt.fakeTranslate("Form", "Draw Component", None, -1))
        self.showUI_checkBox.setText(gqt.fakeTranslate("Form", "Show Setting After Create New Component.", None, -1))

from mgear.core.widgets import DragQListView
