import mgear.core.pyqt as gqt
from mgear.vendor.Qt import QtCore, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(217, 351)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.path_lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.path_lineEdit.setObjectName("path_lineEdit")
        self.horizontalLayout.addWidget(self.path_lineEdit)
        self.load_pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.load_pushButton.setObjectName("load_pushButton")
        self.horizontalLayout.addWidget(self.load_pushButton)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.missingGuide_checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.missingGuide_checkBox.setChecked(True)
        self.missingGuide_checkBox.setObjectName("missingGuide_checkBox")
        self.verticalLayout.addWidget(self.missingGuide_checkBox)
        self.extraGuide_checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.extraGuide_checkBox.setObjectName("extraGuide_checkBox")
        self.verticalLayout.addWidget(self.extraGuide_checkBox)
        self.transform_checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.transform_checkBox.setChecked(True)
        self.transform_checkBox.setObjectName("transform_checkBox")
        self.verticalLayout.addWidget(self.transform_checkBox)
        self.rootSettings_checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.rootSettings_checkBox.setChecked(True)
        self.rootSettings_checkBox.setObjectName("rootSettings_checkBox")
        self.verticalLayout.addWidget(self.rootSettings_checkBox)
        self.compSettings_checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.compSettings_checkBox.setChecked(True)
        self.compSettings_checkBox.setObjectName("compSettings_checkBox")
        self.verticalLayout.addWidget(self.compSettings_checkBox)
        self.customStep_checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.customStep_checkBox.setChecked(True)
        self.customStep_checkBox.setObjectName("customStep_checkBox")
        self.verticalLayout.addWidget(self.customStep_checkBox)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.runTest_pushButton = QtWidgets.QPushButton(Form)
        self.runTest_pushButton.setObjectName("runTest_pushButton")
        self.verticalLayout_2.addWidget(self.runTest_pushButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(gqt.fakeTranslate("Form", "Form", None, -1))
        self.groupBox_2.setTitle(gqt.fakeTranslate("Form", "Master Guide Template", None, -1))
        self.load_pushButton.setText(gqt.fakeTranslate("Form", "...", None, -1))
        self.groupBox.setTitle(gqt.fakeTranslate("Form", "Differences Test Options", None, -1))
        self.missingGuide_checkBox.setText(gqt.fakeTranslate("Form", "Missing Guide Component", None, -1))
        self.extraGuide_checkBox.setText(gqt.fakeTranslate("Form", "Extra  Guide Component", None, -1))
        self.transform_checkBox.setText(gqt.fakeTranslate("Form", "Component Transforms", None, -1))
        self.rootSettings_checkBox.setText(gqt.fakeTranslate("Form", "Root Settings", None, -1))
        self.compSettings_checkBox.setText(gqt.fakeTranslate("Form", "Component  Settings", None, -1))
        self.customStep_checkBox.setText(gqt.fakeTranslate("Form", "Custom Steps", None, -1))
        self.runTest_pushButton.setText(gqt.fakeTranslate("Form", "Run Differences Test", None, -1))

