import mgear.core.pyqt as gqt
from mgear.vendor.Qt import QtCore, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(238, 538)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.keepLength_checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.keepLength_checkBox.setText("Keep Length")
        self.keepLength_checkBox.setObjectName("keepLength_checkBox")
        self.verticalLayout.addWidget(self.keepLength_checkBox)
        self.gridLayout_5.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.jntNb_label = QtWidgets.QLabel(self.groupBox_3)
        self.jntNb_label.setObjectName("jntNb_label")
        self.horizontalLayout.addWidget(self.jntNb_label)
        self.jntNb_spinBox = QtWidgets.QSpinBox(self.groupBox_3)
        self.jntNb_spinBox.setMinimum(3)
        self.jntNb_spinBox.setMaximum(999)
        self.jntNb_spinBox.setProperty("value", 3)
        self.jntNb_spinBox.setObjectName("jntNb_spinBox")
        self.horizontalLayout.addWidget(self.jntNb_spinBox)
        self.gridLayout_6.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.tipRefArray_groupBox = QtWidgets.QGroupBox(Form)
        self.tipRefArray_groupBox.setObjectName("tipRefArray_groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tipRefArray_groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tipRefArray_horizontalLayout = QtWidgets.QHBoxLayout()
        self.tipRefArray_horizontalLayout.setObjectName("tipRefArray_horizontalLayout")
        self.tipRefArray_verticalLayout_1 = QtWidgets.QVBoxLayout()
        self.tipRefArray_verticalLayout_1.setObjectName("tipRefArray_verticalLayout_1")
        self.tipRefArray_listWidget = QtWidgets.QListWidget(self.tipRefArray_groupBox)
        self.tipRefArray_listWidget.setDragDropOverwriteMode(True)
        self.tipRefArray_listWidget.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.tipRefArray_listWidget.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.tipRefArray_listWidget.setAlternatingRowColors(True)
        self.tipRefArray_listWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tipRefArray_listWidget.setSelectionRectVisible(False)
        self.tipRefArray_listWidget.setObjectName("tipRefArray_listWidget")
        self.tipRefArray_verticalLayout_1.addWidget(self.tipRefArray_listWidget)
        self.tipRefArray_copyRef_pushButton = QtWidgets.QPushButton(self.tipRefArray_groupBox)
        self.tipRefArray_copyRef_pushButton.setObjectName("tipRefArray_copyRef_pushButton")
        self.tipRefArray_verticalLayout_1.addWidget(self.tipRefArray_copyRef_pushButton)
        self.tipRefArray_horizontalLayout.addLayout(self.tipRefArray_verticalLayout_1)
        self.tipRefArray_verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.tipRefArray_verticalLayout_2.setObjectName("tipRefArray_verticalLayout_2")
        self.tipRefArrayAdd_pushButton = QtWidgets.QPushButton(self.tipRefArray_groupBox)
        self.tipRefArrayAdd_pushButton.setObjectName("tipRefArrayAdd_pushButton")
        self.tipRefArray_verticalLayout_2.addWidget(self.tipRefArrayAdd_pushButton)
        self.tipRefArrayRemove_pushButton = QtWidgets.QPushButton(self.tipRefArray_groupBox)
        self.tipRefArrayRemove_pushButton.setObjectName("tipRefArrayRemove_pushButton")
        self.tipRefArray_verticalLayout_2.addWidget(self.tipRefArrayRemove_pushButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.tipRefArray_verticalLayout_2.addItem(spacerItem)
        self.tipRefArray_horizontalLayout.addLayout(self.tipRefArray_verticalLayout_2)
        self.gridLayout_4.addLayout(self.tipRefArray_horizontalLayout, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.tipRefArray_groupBox, 3, 0, 1, 1)
        self.rootRefArray_groupBox = QtWidgets.QGroupBox(Form)
        self.rootRefArray_groupBox.setObjectName("rootRefArray_groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.rootRefArray_groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.rootRefArray_horizontalLayout = QtWidgets.QHBoxLayout()
        self.rootRefArray_horizontalLayout.setObjectName("rootRefArray_horizontalLayout")
        self.rootRefArray_verticalLayout_1 = QtWidgets.QVBoxLayout()
        self.rootRefArray_verticalLayout_1.setObjectName("rootRefArray_verticalLayout_1")
        self.rootRefArray_listWidget = QtWidgets.QListWidget(self.rootRefArray_groupBox)
        self.rootRefArray_listWidget.setDragDropOverwriteMode(True)
        self.rootRefArray_listWidget.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.rootRefArray_listWidget.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.rootRefArray_listWidget.setAlternatingRowColors(True)
        self.rootRefArray_listWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.rootRefArray_listWidget.setSelectionRectVisible(False)
        self.rootRefArray_listWidget.setObjectName("rootRefArray_listWidget")
        self.rootRefArray_verticalLayout_1.addWidget(self.rootRefArray_listWidget)
        self.rootRefArray_copyRef_pushButton = QtWidgets.QPushButton(self.rootRefArray_groupBox)
        self.rootRefArray_copyRef_pushButton.setObjectName("rootRefArray_copyRef_pushButton")
        self.rootRefArray_verticalLayout_1.addWidget(self.rootRefArray_copyRef_pushButton)
        self.rootRefArray_horizontalLayout.addLayout(self.rootRefArray_verticalLayout_1)
        self.rootRefArray_verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.rootRefArray_verticalLayout_2.setObjectName("rootRefArray_verticalLayout_2")
        self.rootRefArrayAdd_pushButton = QtWidgets.QPushButton(self.rootRefArray_groupBox)
        self.rootRefArrayAdd_pushButton.setObjectName("rootRefArrayAdd_pushButton")
        self.rootRefArray_verticalLayout_2.addWidget(self.rootRefArrayAdd_pushButton)
        self.rootRefArrayRemove_pushButton = QtWidgets.QPushButton(self.rootRefArray_groupBox)
        self.rootRefArrayRemove_pushButton.setObjectName("rootRefArrayRemove_pushButton")
        self.rootRefArray_verticalLayout_2.addWidget(self.rootRefArrayRemove_pushButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.rootRefArray_verticalLayout_2.addItem(spacerItem1)
        self.rootRefArray_horizontalLayout.addLayout(self.rootRefArray_verticalLayout_2)
        self.gridLayout_3.addLayout(self.rootRefArray_horizontalLayout, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.rootRefArray_groupBox, 2, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(gqt.fakeTranslate("Form", "Form", None, -1))
        self.groupBox_3.setTitle(gqt.fakeTranslate("Form", "Joint Options", None, -1))
        self.jntNb_label.setText(gqt.fakeTranslate("Form", "Joints Number", None, -1))
        self.tipRefArray_groupBox.setTitle(gqt.fakeTranslate("Form", "Tip Reference Array", None, -1))
        self.tipRefArray_copyRef_pushButton.setText(gqt.fakeTranslate("Form", "Copy from Root Ref", None, -1))
        self.tipRefArrayAdd_pushButton.setText(gqt.fakeTranslate("Form", "<<", None, -1))
        self.tipRefArrayRemove_pushButton.setText(gqt.fakeTranslate("Form", ">>", None, -1))
        self.rootRefArray_groupBox.setTitle(gqt.fakeTranslate("Form", "Root Reference Array", None, -1))
        self.rootRefArray_copyRef_pushButton.setText(gqt.fakeTranslate("Form", "Copy from Tip Ref", None, -1))
        self.rootRefArrayAdd_pushButton.setText(gqt.fakeTranslate("Form", "<<", None, -1))
        self.rootRefArrayRemove_pushButton.setText(gqt.fakeTranslate("Form", ">>", None, -1))

        