from mgear.core import pyqt
from mgear.vendor.Qt import QtCore, QtWidgets


class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(359, 526)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.rig_tab = QtWidgets.QWidget()
        self.rig_tab.setObjectName("rig_tab")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.rig_tab)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.createRoot_pushButton = QtWidgets.QPushButton(self.rig_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.createRoot_pushButton.sizePolicy().hasHeightForWidth())
        self.createRoot_pushButton.setSizePolicy(sizePolicy)
        self.createRoot_pushButton.setObjectName("createRoot_pushButton")
        self.gridLayout_6.addWidget(self.createRoot_pushButton, 0, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.rig_tab)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.createCtl_lineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.createCtl_lineEdit.sizePolicy().hasHeightForWidth())
        self.createCtl_lineEdit.setSizePolicy(sizePolicy)
        self.createCtl_lineEdit.setMinimumSize(QtCore.QSize(150, 0))
        self.createCtl_lineEdit.setObjectName("createCtl_lineEdit")
        self.gridLayout_2.addWidget(self.createCtl_lineEdit, 1, 0, 1, 1)
        self.createCtl_pushButton = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.createCtl_pushButton.sizePolicy().hasHeightForWidth())
        self.createCtl_pushButton.setSizePolicy(sizePolicy)
        self.createCtl_pushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.createCtl_pushButton.setObjectName("createCtl_pushButton")
        self.gridLayout_2.addWidget(self.createCtl_pushButton, 3, 0, 1, 1)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.side_comboBox = QtWidgets.QComboBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.side_comboBox.sizePolicy().hasHeightForWidth())
        self.side_comboBox.setSizePolicy(sizePolicy)
        self.side_comboBox.setObjectName("side_comboBox")
        self.side_comboBox.addItem("")
        self.side_comboBox.addItem("")
        self.side_comboBox.addItem("")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.side_comboBox)
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.position_comboBox = QtWidgets.QComboBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.position_comboBox.sizePolicy().hasHeightForWidth())
        self.position_comboBox.setSizePolicy(sizePolicy)
        self.position_comboBox.setObjectName("position_comboBox")
        self.position_comboBox.addItem("")
        self.position_comboBox.addItem("")
        self.position_comboBox.addItem("")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.position_comboBox)
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.shape_comboBox = QtWidgets.QComboBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shape_comboBox.sizePolicy().hasHeightForWidth())
        self.shape_comboBox.setSizePolicy(sizePolicy)
        self.shape_comboBox.setObjectName("shape_comboBox")
        self.shape_comboBox.addItem("")
        self.shape_comboBox.addItem("")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.shape_comboBox)
        self.gridLayout_2.addLayout(self.formLayout_2, 2, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.rig_tab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.remove_pushButton = QtWidgets.QPushButton(self.groupBox_4)
        self.remove_pushButton.setMinimumSize(QtCore.QSize(45, 50))
        self.remove_pushButton.setObjectName("remove_pushButton")
        self.horizontalLayout.addWidget(self.remove_pushButton)
        self.add_pushButton = QtWidgets.QPushButton(self.groupBox_4)
        self.add_pushButton.setMinimumSize(QtCore.QSize(45, 50))
        self.add_pushButton.setObjectName("add_pushButton")
        self.horizontalLayout.addWidget(self.add_pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.selectAffected_pushButton = QtWidgets.QPushButton(self.groupBox_4)
        self.selectAffected_pushButton.setObjectName("selectAffected_pushButton")
        self.verticalLayout_2.addWidget(self.selectAffected_pushButton)
        self.gridLayout_4.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_4, 1, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.editPivot_pushButton = QtWidgets.QPushButton(self.groupBox)
        self.editPivot_pushButton.setObjectName("editPivot_pushButton")
        self.verticalLayout.addWidget(self.editPivot_pushButton)
        self.setPivot_pushButton = QtWidgets.QPushButton(self.groupBox)
        self.setPivot_pushButton.setObjectName("setPivot_pushButton")
        self.verticalLayout.addWidget(self.setPivot_pushButton)
        self.reParentPivot_pushButton = QtWidgets.QPushButton(self.groupBox)
        self.reParentPivot_pushButton.setObjectName("reParentPivot_pushButton")
        self.verticalLayout.addWidget(self.reParentPivot_pushButton)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_2, 2, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.rig_tab)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.suffix_label = QtWidgets.QLabel(self.groupBox_5)
        self.suffix_label.setObjectName("suffix_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.suffix_label)
        self.autoBuild_lineEdit = QtWidgets.QLineEdit(self.groupBox_5)
        self.autoBuild_lineEdit.setObjectName("autoBuild_lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.autoBuild_lineEdit)
        self.gridLayout_5.addLayout(self.formLayout, 0, 0, 1, 1)
        self.autoRig_pushButton = QtWidgets.QPushButton(self.groupBox_5)
        self.autoRig_pushButton.setObjectName("autoRig_pushButton")
        self.gridLayout_5.addWidget(self.autoRig_pushButton, 1, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_5, 3, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(17, 31, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem, 4, 0, 1, 1)
        self.tabWidget.addTab(self.rig_tab, "")
        self.extraConfig_tab = QtWidgets.QWidget()
        self.extraConfig_tab.setObjectName("extraConfig_tab")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.extraConfig_tab)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.groupBox_6 = QtWidgets.QGroupBox(self.extraConfig_tab)
        self.groupBox_6.setObjectName("groupBox_6")
        self.formLayout_3 = QtWidgets.QFormLayout(self.groupBox_6)
        self.formLayout_3.setObjectName("formLayout_3")
        self.rootName_label = QtWidgets.QLabel(self.groupBox_6)
        self.rootName_label.setObjectName("rootName_label")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.rootName_label)
        self.rootName_lineEdit = QtWidgets.QLineEdit(self.groupBox_6)
        self.rootName_lineEdit.setObjectName("rootName_lineEdit")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.rootName_lineEdit)
        self.gridLayout_9.addWidget(self.groupBox_6, 0, 0, 1, 1)
        self.groupBox_8 = QtWidgets.QGroupBox(self.extraConfig_tab)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.fixSize_checkBox = QtWidgets.QCheckBox(self.groupBox_8)
        self.fixSize_checkBox.setObjectName("fixSize_checkBox")
        self.gridLayout_8.addWidget(self.fixSize_checkBox, 1, 0, 1, 1)
        self.worldCenter_checkBox = QtWidgets.QCheckBox(self.groupBox_8)
        self.worldCenter_checkBox.setChecked(True)
        self.worldCenter_checkBox.setTristate(False)
        self.worldCenter_checkBox.setObjectName("worldCenter_checkBox")
        self.gridLayout_8.addWidget(self.worldCenter_checkBox, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox_8)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.mainCtlShape_comboBox = QtWidgets.QComboBox(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainCtlShape_comboBox.sizePolicy().hasHeightForWidth())
        self.mainCtlShape_comboBox.setSizePolicy(sizePolicy)
        self.mainCtlShape_comboBox.setObjectName("mainCtlShape_comboBox")
        self.mainCtlShape_comboBox.addItem("")
        self.mainCtlShape_comboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.mainCtlShape_comboBox)
        self.gridLayout_8.addLayout(self.horizontalLayout_2, 3, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_8)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.fixSize_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_8)
        self.fixSize_doubleSpinBox.setMaximum(9999.99)
        self.fixSize_doubleSpinBox.setSingleStep(10.0)
        self.fixSize_doubleSpinBox.setProperty("value", 100.0)
        self.fixSize_doubleSpinBox.setObjectName("fixSize_doubleSpinBox")
        self.horizontalLayout_3.addWidget(self.fixSize_doubleSpinBox)
        self.gridLayout_8.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.groupBox_8)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.worldCtlShape_comboBox = QtWidgets.QComboBox(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.worldCtlShape_comboBox.sizePolicy().hasHeightForWidth())
        self.worldCtlShape_comboBox.setSizePolicy(sizePolicy)
        self.worldCtlShape_comboBox.setObjectName("worldCtlShape_comboBox")
        self.worldCtlShape_comboBox.addItem("")
        self.worldCtlShape_comboBox.addItem("")
        self.horizontalLayout_4.addWidget(self.worldCtlShape_comboBox)
        self.gridLayout_8.addLayout(self.horizontalLayout_4, 6, 0, 1, 1)
        self.worldCtl_checkBox = QtWidgets.QCheckBox(self.groupBox_8)
        self.worldCtl_checkBox.setChecked(True)
        self.worldCtl_checkBox.setObjectName("worldCtl_checkBox")
        self.gridLayout_8.addWidget(self.worldCtl_checkBox, 5, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.groupBox_8)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_8.addWidget(self.line, 4, 0, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_8, 1, 0, 1, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(self.extraConfig_tab)
        self.groupBox_7.setObjectName("groupBox_7")
        self.formLayout_4 = QtWidgets.QFormLayout(self.groupBox_7)
        self.formLayout_4.setObjectName("formLayout_4")
        self.extraSets_label = QtWidgets.QLabel(self.groupBox_7)
        self.extraSets_label.setObjectName("extraSets_label")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.extraSets_label)
        self.extraSets_lineEdit = QtWidgets.QLineEdit(self.groupBox_7)
        self.extraSets_lineEdit.setObjectName("extraSets_lineEdit")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.extraSets_lineEdit)
        self.gridLayout_9.addWidget(self.groupBox_7, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem1, 3, 0, 1, 1)
        self.tabWidget.addTab(self.extraConfig_tab, "")
        self.gridLayout_7.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 359, 21))
        self.menubar.setObjectName("menubar")
        self.menuIO = QtWidgets.QMenu(self.menubar)
        self.menuIO.setObjectName("menuIO")
        self.menuConvert = QtWidgets.QMenu(self.menubar)
        self.menuConvert.setObjectName("menuConvert")
        self.menuDelete = QtWidgets.QMenu(self.menubar)
        self.menuDelete.setObjectName("menuDelete")
        self.menuAuto = QtWidgets.QMenu(self.menubar)
        self.menuAuto.setObjectName("menuAuto")
        MainWindow.setMenuBar(self.menubar)
        self.export_action = QtWidgets.QAction(MainWindow)
        self.export_action.setObjectName("export_action")
        self.import_action = QtWidgets.QAction(MainWindow)
        self.import_action.setObjectName("import_action")
        self.convertToShifterRig_action = QtWidgets.QAction(MainWindow)
        self.convertToShifterRig_action.setObjectName("convertToShifterRig_action")
        self.createShifterGuide_action = QtWidgets.QAction(MainWindow)
        self.createShifterGuide_action.setObjectName("createShifterGuide_action")
        self.deleteRig_action = QtWidgets.QAction(MainWindow)
        self.deleteRig_action.setObjectName("deleteRig_action")
        self.deletePivot_action = QtWidgets.QAction(MainWindow)
        self.deletePivot_action.setObjectName("deletePivot_action")
        self.autoBuild_action = QtWidgets.QAction(MainWindow)
        self.autoBuild_action.setObjectName("autoBuild_action")
        self.menuIO.addAction(self.export_action)
        self.menuIO.addAction(self.import_action)
        self.menuIO.addSeparator()
        self.menuConvert.addAction(self.convertToShifterRig_action)
        self.menuConvert.addAction(self.createShifterGuide_action)
        self.menuDelete.addAction(self.deletePivot_action)
        self.menuDelete.addSeparator()
        self.menuDelete.addAction(self.deleteRig_action)
        self.menuAuto.addAction(self.autoBuild_action)
        self.menubar.addAction(self.menuIO.menuAction())
        self.menubar.addAction(self.menuConvert.menuAction())
        self.menubar.addAction(self.menuDelete.menuAction())
        self.menubar.addAction(self.menuAuto.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(pyqt.fakeTranslate("MainWindow", "MainWindow", None, -1))
        self.createRoot_pushButton.setText(pyqt.fakeTranslate("MainWindow", "Create Root", None, -1))
        self.groupBox_3.setTitle(pyqt.fakeTranslate("MainWindow", "Create Control", None, -1))
        self.createCtl_pushButton.setText(pyqt.fakeTranslate("MainWindow", "Create CTL", None, -1))
        self.label.setText(pyqt.fakeTranslate("MainWindow", "Side Label", None, -1))
        self.side_comboBox.setItemText(0, pyqt.fakeTranslate("MainWindow", "Center", None, -1))
        self.side_comboBox.setItemText(1, pyqt.fakeTranslate("MainWindow", "Left", None, -1))
        self.side_comboBox.setItemText(2, pyqt.fakeTranslate("MainWindow", "Right", None, -1))
        self.label_3.setText(pyqt.fakeTranslate("MainWindow", "Position", None, -1))
        self.position_comboBox.setItemText(0, pyqt.fakeTranslate("MainWindow", "Center of Geometry", None, -1))
        self.position_comboBox.setItemText(1, pyqt.fakeTranslate("MainWindow", "Base of Geometry (Lowest Y axis point )", None, -1))
        self.position_comboBox.setItemText(2, pyqt.fakeTranslate("MainWindow", "World Center", None, -1))
        self.label_2.setText(pyqt.fakeTranslate("MainWindow", "Ctl Shape", None, -1))
        self.shape_comboBox.setItemText(0, pyqt.fakeTranslate("MainWindow", "Circle", None, -1))
        self.shape_comboBox.setItemText(1, pyqt.fakeTranslate("MainWindow", "Cube", None, -1))
        self.groupBox_2.setTitle(pyqt.fakeTranslate("MainWindow", "Edit", None, -1))
        self.groupBox_4.setTitle(pyqt.fakeTranslate("MainWindow", "Elements", None, -1))
        self.remove_pushButton.setText(pyqt.fakeTranslate("MainWindow", "-", None, -1))
        self.add_pushButton.setText(pyqt.fakeTranslate("MainWindow", "+", None, -1))
        self.selectAffected_pushButton.setText(pyqt.fakeTranslate("MainWindow", "Select Affected", None, -1))
        self.groupBox.setTitle(pyqt.fakeTranslate("MainWindow", "Pivot", None, -1))
        self.editPivot_pushButton.setText(pyqt.fakeTranslate("MainWindow", "Edit Pivot", None, -1))
        self.setPivot_pushButton.setText(pyqt.fakeTranslate("MainWindow", "Set Pivot", None, -1))
        self.reParentPivot_pushButton.setText(pyqt.fakeTranslate("MainWindow", "Re-Parent Pivot", None, -1))
        self.groupBox_5.setTitle(pyqt.fakeTranslate("MainWindow", "Auto Rig", None, -1))
        self.suffix_label.setText(pyqt.fakeTranslate("MainWindow", "Suffix Rule", None, -1))
        self.autoBuild_lineEdit.setText(pyqt.fakeTranslate("MainWindow", "geoRoot", None, -1))
        self.autoRig_pushButton.setText(pyqt.fakeTranslate("MainWindow", "Auto Build", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.rig_tab), pyqt.fakeTranslate("MainWindow", "Rig", None, -1))
        self.groupBox_6.setTitle(pyqt.fakeTranslate("MainWindow", "Root", None, -1))
        self.rootName_label.setText(pyqt.fakeTranslate("MainWindow", "Root Name", None, -1))
        self.rootName_lineEdit.setText(pyqt.fakeTranslate("MainWindow", "root", None, -1))
        self.groupBox_8.setTitle(pyqt.fakeTranslate("MainWindow", "Main Controls  (World, Local, Global)", None, -1))
        self.fixSize_checkBox.setText(pyqt.fakeTranslate("MainWindow", "Use fix size", None, -1))
        self.worldCenter_checkBox.setText(pyqt.fakeTranslate("MainWindow", "Main controls in World Center", None, -1))
        self.label_5.setText(pyqt.fakeTranslate("MainWindow", "Local/Global Ctl Shape", None, -1))
        self.mainCtlShape_comboBox.setItemText(0, pyqt.fakeTranslate("MainWindow", "Square", None, -1))
        self.mainCtlShape_comboBox.setItemText(1, pyqt.fakeTranslate("MainWindow", "Circle", None, -1))
        self.label_4.setText(pyqt.fakeTranslate("MainWindow", "Fix Size", None, -1))
        self.label_6.setText(pyqt.fakeTranslate("MainWindow", "World Ctl Shape", None, -1))
        self.worldCtlShape_comboBox.setItemText(0, pyqt.fakeTranslate("MainWindow", "Circle", None, -1))
        self.worldCtlShape_comboBox.setItemText(1, pyqt.fakeTranslate("MainWindow", "Sphere", None, -1))
        self.worldCtl_checkBox.setText(pyqt.fakeTranslate("MainWindow", "Create World Ctl", None, -1))
        self.groupBox_7.setTitle(pyqt.fakeTranslate("MainWindow", "Custom Sets", None, -1))
        self.extraSets_label.setText(pyqt.fakeTranslate("MainWindow", "Extra CTL Sets", None, -1))
        self.extraSets_lineEdit.setText(pyqt.fakeTranslate("MainWindow", "animSets.basic", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.extraConfig_tab), pyqt.fakeTranslate("MainWindow", "Extra Config", None, -1))
        self.menuIO.setTitle(pyqt.fakeTranslate("MainWindow", "File", None, -1))
        self.menuConvert.setTitle(pyqt.fakeTranslate("MainWindow", "Convert", None, -1))
        self.menuDelete.setTitle(pyqt.fakeTranslate("MainWindow", "Delete", None, -1))
        self.menuAuto.setTitle(pyqt.fakeTranslate("MainWindow", "Auto", None, -1))
        self.export_action.setText(pyqt.fakeTranslate("MainWindow", "Export Config", None, -1))
        self.import_action.setText(pyqt.fakeTranslate("MainWindow", "Import Config", None, -1))
        self.convertToShifterRig_action.setText(pyqt.fakeTranslate("MainWindow", "Convert to Shifter Rig", None, -1))
        self.createShifterGuide_action.setText(pyqt.fakeTranslate("MainWindow", "Create Shifter Guide", None, -1))
        self.deleteRig_action.setText(pyqt.fakeTranslate("MainWindow", "Delete Rig", None, -1))
        self.deletePivot_action.setText(pyqt.fakeTranslate("MainWindow", "Delete Pivot", None, -1))
        self.autoBuild_action.setText(pyqt.fakeTranslate("MainWindow", "Auto Build", None, -1))
