# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/George/Library/Preferences/Autodesk/maya/GitHub/maglev/maglev/tools/setup/gimmickSetup/gimmickSetupUI.ui',
# licensing of '/Users/George/Library/Preferences/Autodesk/maya/GitHub/maglev/maglev/tools/setup/gimmickSetup/gimmickSetupUI.ui' applies.
#
# Created: Sun Sep 25 17:04:38 2022
#      by: pyside2-uic  running on PySide2 5.12.5
#
# WARNING! All changes made in this file will be lost!

import mgear.core.pyqt as gqt
from mgear.vendor.Qt import QtCore, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(388, 347)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.creation_grpupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.creation_grpupBox.sizePolicy().hasHeightForWidth())
        self.creation_grpupBox.setSizePolicy(sizePolicy)
        self.creation_grpupBox.setMaximumSize(QtCore.QSize(16777215, 140))
        self.creation_grpupBox.setObjectName("creation_grpupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.creation_grpupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.creation_side_horizontalLayout = QtWidgets.QHBoxLayout()
        self.creation_side_horizontalLayout.setObjectName("creation_side_horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.creation_side_horizontalLayout.addItem(spacerItem)
        self.creation_side_left_radioButton = QtWidgets.QRadioButton(self.creation_grpupBox)
        self.creation_side_left_radioButton.setChecked(True)
        self.creation_side_left_radioButton.setObjectName("creation_side_left_radioButton")
        self.creation_side_horizontalLayout.addWidget(self.creation_side_left_radioButton)
        self.creation_side_center_radioButton = QtWidgets.QRadioButton(self.creation_grpupBox)
        self.creation_side_center_radioButton.setObjectName("creation_side_center_radioButton")
        self.creation_side_horizontalLayout.addWidget(self.creation_side_center_radioButton)
        self.creation_side_right_radioButton = QtWidgets.QRadioButton(self.creation_grpupBox)
        self.creation_side_right_radioButton.setObjectName("creation_side_right_radioButton")
        self.creation_side_horizontalLayout.addWidget(self.creation_side_right_radioButton)
        spacerItem1 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.creation_side_horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.creation_side_horizontalLayout)
        self.creation_horizontalLayout = QtWidgets.QHBoxLayout()
        self.creation_horizontalLayout.setSpacing(0)
        self.creation_horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.creation_horizontalLayout.setContentsMargins(-1, -1, -1, 0)
        self.creation_horizontalLayout.setObjectName("creation_horizontalLayout")
        self.blendJoint_pushButton = QtWidgets.QPushButton(self.creation_grpupBox)
        self.blendJoint_pushButton.setObjectName("blendJoint_pushButton")
        self.creation_horizontalLayout.addWidget(self.blendJoint_pushButton)
        spacerItem2 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.creation_horizontalLayout.addItem(spacerItem2)
        self.supportJoint_pushButton = QtWidgets.QPushButton(self.creation_grpupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.supportJoint_pushButton.sizePolicy().hasHeightForWidth())
        self.supportJoint_pushButton.setSizePolicy(sizePolicy)
        self.supportJoint_pushButton.setObjectName("supportJoint_pushButton")
        self.creation_horizontalLayout.addWidget(self.supportJoint_pushButton)
        self.verticalLayout_2.addLayout(self.creation_horizontalLayout)
        self.mirrorGimmick_pushButton = QtWidgets.QPushButton(self.creation_grpupBox)
        self.mirrorGimmick_pushButton.setObjectName("mirrorGimmick_pushButton")
        self.verticalLayout_2.addWidget(self.mirrorGimmick_pushButton)
        self.verticalLayout.addWidget(self.creation_grpupBox)
        self.utility_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.utility_groupBox.setObjectName("utility_groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.utility_groupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.utility_verticalLayout = QtWidgets.QVBoxLayout()
        self.utility_verticalLayout.setObjectName("utility_verticalLayout")
        self.utility_horizontalLayout = QtWidgets.QHBoxLayout()
        self.utility_horizontalLayout.setContentsMargins(-1, -1, 0, 0)
        self.utility_horizontalLayout.setObjectName("utility_horizontalLayout")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.utility_horizontalLayout.addItem(spacerItem3)
        self.utility_all_checkBox = QtWidgets.QCheckBox(self.utility_groupBox)
        self.utility_all_checkBox.setObjectName("utility_all_checkBox")
        self.utility_horizontalLayout.addWidget(self.utility_all_checkBox)
        spacerItem4 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.utility_horizontalLayout.addItem(spacerItem4)
        self.utility_left_checkBox = QtWidgets.QCheckBox(self.utility_groupBox)
        self.utility_left_checkBox.setChecked(True)
        self.utility_left_checkBox.setObjectName("utility_left_checkBox")
        self.utility_horizontalLayout.addWidget(self.utility_left_checkBox)
        self.utility_center_checkBox = QtWidgets.QCheckBox(self.utility_groupBox)
        self.utility_center_checkBox.setObjectName("utility_center_checkBox")
        self.utility_horizontalLayout.addWidget(self.utility_center_checkBox)
        self.utility_right_checkBox = QtWidgets.QCheckBox(self.utility_groupBox)
        self.utility_right_checkBox.setObjectName("utility_right_checkBox")
        self.utility_horizontalLayout.addWidget(self.utility_right_checkBox)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.utility_horizontalLayout.addItem(spacerItem5)
        self.utility_verticalLayout.addLayout(self.utility_horizontalLayout)
        self.select_pushButton = QtWidgets.QPushButton(self.utility_groupBox)
        self.select_pushButton.setObjectName("select_pushButton")
        self.utility_verticalLayout.addWidget(self.select_pushButton)
        self.delete_pushButton = QtWidgets.QPushButton(self.utility_groupBox)
        self.delete_pushButton.setObjectName("delete_pushButton")
        self.utility_verticalLayout.addWidget(self.delete_pushButton)
        self.horizontalLayout_2.addLayout(self.utility_verticalLayout)
        self.verticalLayout.addWidget(self.utility_groupBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar()
        self.menubar.setGeometry(QtCore.QRect(0, 0, 388, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.importGimmick_menuAction = QtWidgets.QAction(MainWindow)
        self.importGimmick_menuAction.setObjectName("importGimmick_menuAction")
        self.exportGimmick_menuAction = QtWidgets.QAction(MainWindow)
        self.exportGimmick_menuAction.setObjectName("exportGimmick_menuAction")
        self.menuFile.addAction(self.importGimmick_menuAction)
        self.menuFile.addAction(self.exportGimmick_menuAction)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Gimmick Setup", None, -1))
        self.creation_grpupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "Gimmick Creation", None, -1))
        self.creation_side_left_radioButton.setText(QtWidgets.QApplication.translate("MainWindow", "Left", None, -1))
        self.creation_side_center_radioButton.setText(QtWidgets.QApplication.translate("MainWindow", "Center", None, -1))
        self.creation_side_right_radioButton.setText(QtWidgets.QApplication.translate("MainWindow", "Right", None, -1))
        self.blendJoint_pushButton.setText(QtWidgets.QApplication.translate("MainWindow", "Blend Joint", None, -1))
        self.supportJoint_pushButton.setText(QtWidgets.QApplication.translate("MainWindow", "Support Joint", None, -1))
        self.mirrorGimmick_pushButton.setText(QtWidgets.QApplication.translate("MainWindow", "Mirror Gimmick", None, -1))
        self.utility_groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "Utility", None, -1))
        self.utility_all_checkBox.setText(QtWidgets.QApplication.translate("MainWindow", "All :", None, -1))
        self.utility_left_checkBox.setText(QtWidgets.QApplication.translate("MainWindow", "Left", None, -1))
        self.utility_center_checkBox.setText(QtWidgets.QApplication.translate("MainWindow", "Center", None, -1))
        self.utility_right_checkBox.setText(QtWidgets.QApplication.translate("MainWindow", "Right", None, -1))
        self.select_pushButton.setText(QtWidgets.QApplication.translate("MainWindow", "Select", None, -1))
        self.delete_pushButton.setText(QtWidgets.QApplication.translate("MainWindow", "Delete", None, -1))
        self.menuFile.setTitle(QtWidgets.QApplication.translate("MainWindow", "File", None, -1))
        self.importGimmick_menuAction.setText(QtWidgets.QApplication.translate("MainWindow", "Import Gimmick Data", None, -1))
        self.exportGimmick_menuAction.setText(QtWidgets.QApplication.translate("MainWindow", "Export Gimmick Data", None, -1))

